services:
  - type: web
    name: jubair-boot-house
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python init_schema.py && uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-10000}"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
    healthCheckPath: /
